################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
code \
libraries/infineon_libraries/Configurations \
libraries/infineon_libraries/Infra/Platform/Tricore/Compilers \
libraries/infineon_libraries/Infra/Ssw/TC37A/Tricore \
libraries/infineon_libraries/Service/CpuGeneric/If \
libraries/infineon_libraries/Service/CpuGeneric/StdIf \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Bsp \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Comm \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/General \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Math \
libraries/infineon_libraries/Service/CpuGeneric/SysSe/Time \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Asc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Lin \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Spi \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Asclin/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Can/Can \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Can/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/Icu \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/PwmBc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/PwmHl \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/TPwm \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/Timer \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Ccu6/TimerWithTrigger \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Convctrl/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Cpu/Irq \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Cpu/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Cpu/Trap \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Dma/Dma \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Dma/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Dts/Dts \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Dts/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Edsadc/Edsadc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Edsadc/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Eray/Eray \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Eray/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Evadc/Adc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Evadc/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Fce/Crc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Fce/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Flash/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Geth/Eth \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Geth/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gpt12/IncrEnc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gpt12/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Atom/Pwm \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Atom/PwmHl \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Atom/Timer \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tim/In \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tim/Timer \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tom/Pwm \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tom/PwmHl \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Tom/Timer \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Gtm/Trig \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Hssl/Hssl \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Hssl/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/I2c/I2c \
libraries/infineon_libraries/iLLD/TC37A/Tricore/I2c/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Iom/Driver \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Iom/Iom \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Iom/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Msc/Msc \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Msc/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Mtu/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Pms/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Port/Io \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Port/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5/Psi5 \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5s/Psi5s \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Psi5s/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Qspi/SpiMaster \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Qspi/SpiSlave \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Qspi/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Scu/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Sent/Sent \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Sent/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Smu/Smu \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Smu/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Src/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Stm/Std \
libraries/infineon_libraries/iLLD/TC37A/Tricore/Stm/Timer \
libraries/infineon_libraries/iLLD/TC37A/Tricore/_Impl \
libraries/infineon_libraries/iLLD/TC37A/Tricore/_Lib/DataHandling \
libraries/infineon_libraries/iLLD/TC37A/Tricore/_Lib/InternalMux \
libraries/infineon_libraries/iLLD/TC37A/Tricore/_PinMap \
libraries/zf_common \
libraries/zf_device \
libraries/zf_driver \
user \

